In [ ]:
#### account module, sales 입력 방법 ####

In [27]:
import importlib
import pandas as pd
import numpy as np
import account as acc

In [39]:
importlib.reload(acc)

In [40]:
#### INPUT BASIC DATA ####
mtrt = 26 # months
prd_prjt = 24 # months
#### INPUT BASIC DATA ####


#### INPUT SALES DATA ####
prdtA = acc.account(title="ProductA", tag=("ProductA", "-"), mtrt=mtrt,
                         add_scdd_ipt=pd.Series([70_000.000], index=[0]),
                         sub_scdd_ipt=pd.Series(np.array([0.1, 0.2, 0.2, 0.5])* 70_000.000, index=[1, 9, 17, 24]),
                         note="-")
prdtA.addamt(0, prdtA.add_rsdl(0))

prdtB = acc.account(title="ProductB", tag=("ProductB", "-"), mtrt=mtrt,
                         add_scdd_ipt=pd.Series([70_000.000], index=[0]),
                         sub_scdd_ipt=pd.Series(np.array([0.1, 0.2, 0.2, 0.5])* 70_000.000, index=[1, 9, 17, 24]),
                         note="-")
prdtB.addamt(0, prdtB.add_rsdl(0))

dct = {'prdtA':prdtA, 'prdtB':prdtB}
sales = acc.merge(dct)
#### INPUT SALES DATA ####

In [41]:
sales.dct['prdtA'].sub_exctn([1, 3, 4, 7, 9, 10, 12, 14, 16], [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])
sales.dct['prdtB'].sub_exctn([0, 2, 4, 8, 9, 14, 18, 19, 22], [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [42]:
sales.dct['prdtA'].df

,add_scdd,add_scdd_cum,sub_scdd,sub_scdd_cum,bal_strt,amt_add,amt_add_cum,amt_sub,amt_sub_cum,bal_end,add_rsdl_cum,sub_rsdl_cum
-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,70000.0,70000.0,0.0,0.0,0.0,70000.0,70000.0,0.0,0.0,70000.0,0.0,0.0
1,0.0,70000.0,7000.0,7000.0,70000.0,0.0,70000.0,700.0,700.0,69300.0,0.0,6300.0
2,0.0,70000.0,0.0,7000.0,69300.0,0.0,70000.0,0.0,700.0,69300.0,0.0,6300.0
3,0.0,70000.0,0.0,7000.0,69300.0,0.0,70000.0,700.0,1400.0,68600.0,0.0,5600.0
4,0.0,70000.0,0.0,7000.0,68600.0,0.0,70000.0,700.0,2100.0,67900.0,0.0,4900.0
5,0.0,70000.0,0.0,7000.0,67900.0,0.0,70000.0,0.0,2100.0,67900.0,0.0,4900.0
6,0.0,70000.0,0.0,7000.0,67900.0,0.0,70000.0,0.0,2100.0,67900.0,0.0,4900.0
7,0.0,70000.0,0.0,7000.0,67900.0,0.0,70000.0,700.0,2800.0,67200.0,0.0,4200.0
8,0.0,70000.0,0.0,7000.0,67200.0,0.0,70000.0,0.0,2800.0,67200.0,0.0,4200.0
9,0.0,70000.0,14000.0,21000.0,67200.0,0.0,70000.0,7700.0,10500.0,59500.0,0.0,10500.0
10,0.0,70000.0,0.0,21000.0,59500.0,0.0,70000.0,2100.0,12600.0,57400.0,0.0,8400.0
11,0.0,70000.0,0.0,21000.0,57400.0,0.0,70000.0,0.0,12600.0,57400.0,0.0,8400.0
12,0.0,70000.0,0.0,21000.0,57400.0,0.0,70000.0,2100.0,14700.0,55300.0,0.0,6300.0
13,0.0,70000.0,0.0,21000.0,55300.0,0.0,70000.0,0.0,14700.0,55300.0,0.0,6300.0
14,0.0,70000.0,0.0,21000.0,55300.0,0.0,70000.0,2100.0,16800.0,53200.0,0.0,4200.0
15,0.0,70000.0,0.0,21000.0,53200.0,0.0,70000.0,0.0,16800.0,53200.0,0.0,4200.0
16,0.0,70000.0,0.0,21000.0,53200.0,0.0,70000.0,2100.0,18900.0,51100.0,0.0,2100.0
17,0.0,70000.0,14000.0,35000.0,51100.0,0.0,70000.0,12600.0,31500.0,38500.0,0.0,3500.0
18,0.0,70000.0,0.0,35000.0,38500.0,0.0,70000.0,0.0,31500.0,38500.0,0.0,3500.0
19,0.0,70000.0,0.0,35000.0,38500.0,0.0,70000.0,0.0,31500.0,38500.0,0.0,3500.0
20,0.0,70000.0,0.0,35000.0,38500.0,0.0,70000.0,0.0,31500.0,38500.0,0.0,3500.0
21,0.0,70000.0,0.0,35000.0,38500.0,0.0,70000.0,0.0,31500.0,38500.0,0.0,3500.0
22,0.0,70000.0,0.0,35000.0,38500.0,0.0,70000.0,0.0,31500.0,38500.0,0.0,3500.0
23,0.0,70000.0,0.0,35000.0,38500.0,0.0,70000.0,0.0,31500.0,38500.0,0.0,3500.0
24,0.0,70000.0,35000.0,70000.0,38500.0,0.0,70000.0,31500.0,63000.0,7000.0,0.0,7000.0
25,0.0,70000.0,0.0,70000.0,7000.0,0.0,70000.0,0.0,63000.0,7000.0,0.0,7000.0
26,0.0,70000.0,0.0,70000.0,7000.0,0.0,70000.0,0.0,63000.0,7000.0,0.0,7000.0

In [43]:
sales.dct['prdtB'].df

,add_scdd,add_scdd_cum,sub_scdd,sub_scdd_cum,bal_strt,amt_add,amt_add_cum,amt_sub,amt_sub_cum,bal_end,add_rsdl_cum,sub_rsdl_cum
-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,70000.0,70000.0,0.0,0.0,0.0,70000.0,70000.0,0.0,0.0,70000.0,0.0,0.0
1,0.0,70000.0,7000.0,7000.0,70000.0,0.0,70000.0,700.0,700.0,69300.0,0.0,6300.0
2,0.0,70000.0,0.0,7000.0,69300.0,0.0,70000.0,700.0,1400.0,68600.0,0.0,5600.0
3,0.0,70000.0,0.0,7000.0,68600.0,0.0,70000.0,0.0,1400.0,68600.0,0.0,5600.0
4,0.0,70000.0,0.0,7000.0,68600.0,0.0,70000.0,700.0,2100.0,67900.0,0.0,4900.0
5,0.0,70000.0,0.0,7000.0,67900.0,0.0,70000.0,0.0,2100.0,67900.0,0.0,4900.0
6,0.0,70000.0,0.0,7000.0,67900.0,0.0,70000.0,0.0,2100.0,67900.0,0.0,4900.0
7,0.0,70000.0,0.0,7000.0,67900.0,0.0,70000.0,0.0,2100.0,67900.0,0.0,4900.0
8,0.0,70000.0,0.0,7000.0,67900.0,0.0,70000.0,700.0,2800.0,67200.0,0.0,4200.0
9,0.0,70000.0,14000.0,21000.0,67200.0,0.0,70000.0,7700.0,10500.0,59500.0,0.0,10500.0
10,0.0,70000.0,0.0,21000.0,59500.0,0.0,70000.0,0.0,10500.0,59500.0,0.0,10500.0
11,0.0,70000.0,0.0,21000.0,59500.0,0.0,70000.0,0.0,10500.0,59500.0,0.0,10500.0
12,0.0,70000.0,0.0,21000.0,59500.0,0.0,70000.0,0.0,10500.0,59500.0,0.0,10500.0
13,0.0,70000.0,0.0,21000.0,59500.0,0.0,70000.0,0.0,10500.0,59500.0,0.0,10500.0
14,0.0,70000.0,0.0,21000.0,59500.0,0.0,70000.0,2100.0,12600.0,57400.0,0.0,8400.0
15,0.0,70000.0,0.0,21000.0,57400.0,0.0,70000.0,0.0,12600.0,57400.0,0.0,8400.0
16,0.0,70000.0,0.0,21000.0,57400.0,0.0,70000.0,0.0,12600.0,57400.0,0.0,8400.0
17,0.0,70000.0,14000.0,35000.0,57400.0,0.0,70000.0,8400.0,21000.0,49000.0,0.0,14000.0
18,0.0,70000.0,0.0,35000.0,49000.0,0.0,70000.0,3500.0,24500.0,45500.0,0.0,10500.0
19,0.0,70000.0,0.0,35000.0,45500.0,0.0,70000.0,3500.0,28000.0,42000.0,0.0,7000.0
20,0.0,70000.0,0.0,35000.0,42000.0,0.0,70000.0,0.0,28000.0,42000.0,0.0,7000.0
21,0.0,70000.0,0.0,35000.0,42000.0,0.0,70000.0,0.0,28000.0,42000.0,0.0,7000.0
22,0.0,70000.0,0.0,35000.0,42000.0,0.0,70000.0,3500.0,31500.0,38500.0,0.0,3500.0
23,0.0,70000.0,0.0,35000.0,38500.0,0.0,70000.0,0.0,31500.0,38500.0,0.0,3500.0
24,0.0,70000.0,35000.0,70000.0,38500.0,0.0,70000.0,31500.0,63000.0,7000.0,0.0,7000.0
25,0.0,70000.0,0.0,70000.0,7000.0,0.0,70000.0,0.0,63000.0,7000.0,0.0,7000.0
26,0.0,70000.0,0.0,70000.0,7000.0,0.0,70000.0,0.0,63000.0,7000.0,0.0,7000.0

In [45]:
sales.df

,add_scdd,add_scdd_cum,sub_scdd,sub_scdd_cum,bal_strt,amt_add,amt_add_cum,amt_sub,amt_sub_cum,bal_end,add_rsdl_cum,sub_rsdl_cum
-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,140000.0,140000.0,0.0,0.0,0.0,140000.0,140000.0,0.0,0.0,140000.0,0.0,0.0
1,0.0,140000.0,14000.0,14000.0,140000.0,0.0,140000.0,1400.0,1400.0,138600.0,0.0,12600.0
2,0.0,140000.0,0.0,14000.0,138600.0,0.0,140000.0,700.0,2100.0,137900.0,0.0,11900.0
3,0.0,140000.0,0.0,14000.0,137900.0,0.0,140000.0,700.0,2800.0,137200.0,0.0,11200.0
4,0.0,140000.0,0.0,14000.0,137200.0,0.0,140000.0,1400.0,4200.0,135800.0,0.0,9800.0
5,0.0,140000.0,0.0,14000.0,135800.0,0.0,140000.0,0.0,4200.0,135800.0,0.0,9800.0
6,0.0,140000.0,0.0,14000.0,135800.0,0.0,140000.0,0.0,4200.0,135800.0,0.0,9800.0
7,0.0,140000.0,0.0,14000.0,135800.0,0.0,140000.0,700.0,4900.0,135100.0,0.0,9100.0
8,0.0,140000.0,0.0,14000.0,135100.0,0.0,140000.0,700.0,5600.0,134400.0,0.0,8400.0
9,0.0,140000.0,28000.0,42000.0,134400.0,0.0,140000.0,15400.0,21000.0,119000.0,0.0,21000.0
10,0.0,140000.0,0.0,42000.0,119000.0,0.0,140000.0,2100.0,23100.0,116900.0,0.0,18900.0
11,0.0,140000.0,0.0,42000.0,116900.0,0.0,140000.0,0.0,23100.0,116900.0,0.0,18900.0
12,0.0,140000.0,0.0,42000.0,116900.0,0.0,140000.0,2100.0,25200.0,114800.0,0.0,16800.0
13,0.0,140000.0,0.0,42000.0,114800.0,0.0,140000.0,0.0,25200.0,114800.0,0.0,16800.0
14,0.0,140000.0,0.0,42000.0,114800.0,0.0,140000.0,4200.0,29400.0,110600.0,0.0,12600.0
15,0.0,140000.0,0.0,42000.0,110600.0,0.0,140000.0,0.0,29400.0,110600.0,0.0,12600.0
16,0.0,140000.0,0.0,42000.0,110600.0,0.0,140000.0,2100.0,31500.0,108500.0,0.0,10500.0
17,0.0,140000.0,28000.0,70000.0,108500.0,0.0,140000.0,21000.0,52500.0,87500.0,0.0,17500.0
18,0.0,140000.0,0.0,70000.0,87500.0,0.0,140000.0,3500.0,56000.0,84000.0,0.0,14000.0
19,0.0,140000.0,0.0,70000.0,84000.0,0.0,140000.0,3500.0,59500.0,80500.0,0.0,10500.0
20,0.0,140000.0,0.0,70000.0,80500.0,0.0,140000.0,0.0,59500.0,80500.0,0.0,10500.0
21,0.0,140000.0,0.0,70000.0,80500.0,0.0,140000.0,0.0,59500.0,80500.0,0.0,10500.0
22,0.0,140000.0,0.0,70000.0,80500.0,0.0,140000.0,3500.0,63000.0,77000.0,0.0,7000.0
23,0.0,140000.0,0.0,70000.0,77000.0,0.0,140000.0,0.0,63000.0,77000.0,0.0,7000.0
24,0.0,140000.0,70000.0,140000.0,77000.0,0.0,140000.0,63000.0,126000.0,14000.0,0.0,14000.0
25,0.0,140000.0,0.0,140000.0,14000.0,0.0,140000.0,0.0,126000.0,14000.0,0.0,14000.0
26,0.0,140000.0,0.0,140000.0,14000.0,0.0,140000.0,0.0,126000.0,14000.0,0.0,14000.0

In [47]:
sales.df_var('amt_sub')

       prdtA    prdtB
-1       0.0      0.0
 0       0.0      0.0
 1     700.0    700.0
 2       0.0    700.0
 3     700.0      0.0
 4     700.0    700.0
 5       0.0      0.0
 6       0.0      0.0
 7     700.0      0.0
 8       0.0    700.0
 9    7700.0   7700.0
 10   2100.0      0.0
 11      0.0      0.0
 12   2100.0      0.0
 13      0.0      0.0
 14   2100.0   2100.0
 15      0.0      0.0
 16   2100.0      0.0
 17  12600.0   8400.0
 18      0.0   3500.0
 19      0.0   3500.0
 20      0.0      0.0
 21      0.0      0.0
 22      0.0   3500.0
 23      0.0      0.0
 24  31500.0  31500.0
 25      0.0      0.0
 26      0.0      0.0

In [54]:
sales_rate = sales.df.amt_sub / sales.df.add_scdd_cum

In [56]:
sales_rate * 40_000

-1         NaN
 0         0.0
 1       400.0
 2       200.0
 3       200.0
 4       400.0
 5         0.0
 6         0.0
 7       200.0
 8       200.0
 9      4400.0
 10      600.0
 11        0.0
 12      600.0
 13        0.0
 14     1200.0
 15        0.0
 16      600.0
 17     6000.0
 18     1000.0
 19     1000.0
 20        0.0
 21        0.0
 22     1000.0
 23        0.0
 24    18000.0
 25        0.0
 26        0.0
dtype: float64