In [101]:
import importlib
import pandas as pd
import numpy as np
import account as acc

In [128]:
importlib.reload(acc)

In [129]:
#### INPUT BASIC DATA ####
mtrt = 26 # months
prd_prjt = 24 # months
#### INPUT BASIC DATA ####


#### INPUT SALES DATA ####
sales_prdtA = acc.account(title="ProductA", tag=("ProductA", "-"), mtrt=mtrt,
                         add_scdd_ipt=pd.Series([70_000.000], index=[0]),
                         sub_scdd_ipt=pd.Series(np.array([0.1, 0.2, 0.2, 0.5])* 70_000.000, index=[1, 9, 17, 24]),
                         note="-")
sales_prdtA.addamt(0, sales_prdtA.add_rsdl(0))
#### INPUT SALES DATA ####

In [148]:
sales_prdtA.sub_exctn(14, 0.1)

In [149]:
sales_prdtA.df

,add_scdd,add_scdd_cum,sub_scdd,sub_scdd_cum,bal_strt,amt_add,amt_sub,bal_end,add_rsdl_cum,sub_rsdl_cum
-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,70000.0,70000.0,0.0,0.0,0.0,70000.0,0.0,70000.0,0.0,0.0
1,0.0,70000.0,7000.0,7000.0,70000.0,0.0,700.0,69300.0,0.0,6300.0
2,0.0,70000.0,0.0,7000.0,69300.0,0.0,0.0,69300.0,0.0,6300.0
3,0.0,70000.0,0.0,7000.0,69300.0,0.0,0.0,69300.0,0.0,6300.0
4,0.0,70000.0,0.0,7000.0,69300.0,0.0,700.0,68600.0,0.0,5600.0
5,0.0,70000.0,0.0,7000.0,68600.0,0.0,700.0,67900.0,0.0,4900.0
6,0.0,70000.0,0.0,7000.0,67900.0,0.0,0.0,67900.0,0.0,4900.0
7,0.0,70000.0,0.0,7000.0,67900.0,0.0,0.0,67900.0,0.0,4900.0
8,0.0,70000.0,0.0,7000.0,67900.0,0.0,0.0,67900.0,0.0,4900.0
9,0.0,70000.0,14000.0,21000.0,67900.0,0.0,4200.0,63700.0,0.0,14700.0
10,0.0,70000.0,0.0,21000.0,63700.0,0.0,0.0,63700.0,0.0,14700.0
11,0.0,70000.0,0.0,21000.0,63700.0,0.0,2100.0,61600.0,0.0,12600.0
12,0.0,70000.0,0.0,21000.0,61600.0,0.0,2100.0,59500.0,0.0,10500.0
13,0.0,70000.0,0.0,21000.0,59500.0,0.0,0.0,59500.0,0.0,10500.0
14,0.0,70000.0,0.0,21000.0,59500.0,0.0,2100.0,57400.0,0.0,8400.0
15,0.0,70000.0,0.0,21000.0,57400.0,0.0,0.0,57400.0,0.0,8400.0
16,0.0,70000.0,0.0,21000.0,57400.0,0.0,0.0,57400.0,0.0,8400.0
17,0.0,70000.0,14000.0,35000.0,57400.0,0.0,8400.0,49000.0,0.0,14000.0
18,0.0,70000.0,0.0,35000.0,49000.0,0.0,3500.0,45500.0,0.0,10500.0
19,0.0,70000.0,0.0,35000.0,45500.0,0.0,3500.0,42000.0,0.0,7000.0
20,0.0,70000.0,0.0,35000.0,42000.0,0.0,0.0,42000.0,0.0,7000.0
21,0.0,70000.0,0.0,35000.0,42000.0,0.0,0.0,42000.0,0.0,7000.0
22,0.0,70000.0,0.0,35000.0,42000.0,0.0,3500.0,38500.0,0.0,3500.0
23,0.0,70000.0,0.0,35000.0,38500.0,0.0,0.0,38500.0,0.0,3500.0
24,0.0,70000.0,35000.0,70000.0,38500.0,0.0,31500.0,7000.0,0.0,7000.0
25,0.0,70000.0,0.0,70000.0,7000.0,0.0,7000.0,0.0,0.0,0.0
26,0.0,70000.0,0.0,70000.0,0.0,0.0,0.0,0.0,0.0,0.0